version: "3.10"
services:
  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Пароль для аутентификации в Redis
    command: redis-server --requirepass ${REDIS_PASSWORD} # Указываем пароль при запуске Redis

  web:
    build: .
    depends_on:
      - redis
    command: >
      bash -c "uvicorn src.app:app --host 0.0.0.0 --port 8090"
    ports:
      - "8090:8090"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
    image: derelia/big_data_lab_second:latest

volumes:
  redis_data:
